//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmbracoHomework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Submission
    {
        public int Id { get; set; }
          [Required(ErrorMessage = "Required")]
        //  [Remote("IsUserNameAvailable", "Submissions", ErrorMessage = "Name already in use")]
        //  [RemoteClientServer("IsUserNameAvailable", "Submissions", ErrorMessage = "Name already in use")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> Age { get; set; }

        [Required(ErrorMessage = "Required")]
        [RemoteClientServer("IsSerialnumberAvailable", "Submissions", ErrorMessage = "Serialnumber already in use")]
        public Nullable<System.Guid> Serialnumber { get; set; }

        [Required(ErrorMessage = "Required")]
        [Validation(ErrorMessage = "Age must be at least 18", MinAge = 18)]
        public Nullable<System.DateTime> DOB { get; set; }    
        public virtual Serialnumber Serialnumber1 { get; set; }
    }
}
